/*

    OpenGL ES loader generated by glad 0.1.34 on Tue Sep 19 02:17:07 2023.

    Language/Generator: D
    Specification: gl
    APIs: gles2=3.0
    Profile: compatibility
    Extensions:
        GL_AMD_program_binary_Z400
    Loader: True
    Local files: False
    Omit khrplatform: False
    Reproducible: False

    Commandline:
        --profile="compatibility" --api="gles2=3.0" --generator="d" --spec="gl" --extensions="GL_AMD_program_binary_Z400"
    Online:
        https://glad.dav1d.de/#profile=compatibility&language=d&specification=gl&loader=on&api=gles2%3D3.0&extensions=GL_AMD_program_binary_Z400
*/

module glad.gl.all;


public import glad.gl.funcs;
public import glad.gl.ext;
public import glad.gl.enums;
public import glad.gl.types;
